### ISSUE TITLE
데이터 공유 가능 여부

### ISSUE THREAD

**Issue by gyunggyung** [shbictai/narrativeKoGPT2#2]
안녕하세요. 혹시 저작권 만료된 한국 소설의 경우 데이터 공유가 가능할까요?

감사합니다.

**Comment by shbictai** [comment]
혹시 몰라서 직접적인 공유는 어려울거 같습니다.
저희가 테스트에 사용한 데이터로는

1. 국립국어원 언어정보 나눔터에서 이전 소설들에 대한 말뭉치를 직접 받으실 수 도있고, 
2. 구글에서 "동화 텍본"으로 검색
3. 구글에서 "인소 텍본"으로 검색

위 세가지 방법으로 테스트 데이터를 적절하게 찾으실 수 있을것으로 사료됩니다.

**Comment by gyunggyung** [comment]
답변 감사합니다!
ᐧ
